project:
  type: website

format:
  html:
    theme: flatly
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  site-url: ''
  navbar:    
    logo: figures/andi_logo.png
    logo-href: index.md
    background: primary
    search: true    
    collapse-below: lg
    left:
      - text: "Documentation"
        href: index.md
      - text: "Tutorials"
        href: tutorials/tutorials.md
  sidebar:
    style: floating
    
    

metadata-files: [nbdev.yml, sidebar.yml]