project:
  type: website

format:
  html:
    theme: default
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  site-url: ''
  navbar:    
    logo: figures/logo_noname.svg
    logo-href: index.ipynb
    background: primary
    search: true    
    collapse-below: lg
    left:
      - text: "Documentation"
        href: lib_nbs/index_docs.ipynb
      - text: "Tutorials"
        href: tutorials/index_tutorials.ipynb
      - text: "ANDI interactive tool"
        href: https://andi-app.herokuapp.com/andi_app
          
  sidebar:
    style: floating
    
    

metadata-files: [nbdev.yml, sidebar.yml]