name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
	- uses: actions/setup-python@v4
	  with:
	    python-version: '3.10'
	- uses: fastai/workflows/nbdev-ci@master