name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu, macos]
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}-latest
    steps: [uses: fastai/workflows/nbdev-ci@master]